<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>day_20_text</name>
   <tag></tag>
   <elementGuidId>f2a6f034-843a-4694-8e68-a90ec9f23875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-layout/app-package-detail/div/section/div/div[2]/div/div/div[1]/ngx-daterangepicker-material/div/div[2]/div/table/tbody/tr[4]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-layout/app-package-detail/div/section/div/div[2]/div/div/div[1]/ngx-daterangepicker-material/div/div[2]/div/table/tbody/tr[4]/td[4]</value>
   </webElementProperties>
</WebElementEntity>
