<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paket_recommend_santap_siang_button</name>
   <tag></tag>
   <elementGuidId>17468841-0103-48ce-ad88-d7ea9e34018e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-layout/app-dashboard/div/section/div/div[3]/app-swipe-multiple-item/div[3]/ngx-slick-carousel/div/div/div[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Santap Siang Favorit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-layout/app-dashboard/div/section/div/div[3]/app-swipe-multiple-item/div[3]/ngx-slick-carousel/div/div/div[8]</value>
   </webElementProperties>
</WebElementEntity>
